# Generated by Django 2.2.6 on 2019-10-19 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('fname', models.CharField(default='', max_length=100)),
                ('lname', models.CharField(default='', max_length=100)),
                ('headerPic', models.CharField(default='header.png', max_length=300)),
                ('profilePic', models.CharField(default='logo.png', max_length=300)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('occupation', models.CharField(default='', max_length=100)),
                ('shortdescription', models.CharField(default='', max_length=300)),
                ('verified', models.BooleanField(default=False, max_length=100)),
                ('emailverified', models.BooleanField(default=False)),
                ('emailotp', models.CharField(blank=True, max_length=100, null=True)),
                ('is2fa', models.BooleanField(default=False)),
                ('issuspended', models.BooleanField(default=False)),
                ('suspendedtill', models.DateField(blank=True, null=True)),
                ('isPsy', models.BooleanField(default=False)),
                ('ispublic', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
